version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "MeilCli"
    open-pull-requests-limit: 20
  - package-ecosystem: "gradle"
    directory: "/Toolchain/Gradle/dependencies"
    schedule:
      interval: "daily"
    reviewers:
      - "MeilCli"
    open-pull-requests-limit: 20
