name: Automerge

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  check_suite:
    types:
      - completed
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        continue-on-error: true
        if: secrets.MEILCLI_BOT != ''
        with:
          token: ${{ secrets.MEILCLI_BOT }}
          merge-method: merge
