name: Report

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - run: sleep 10s
        name: wait for API&DB synchronized
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: eslint_result
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: detekt_result
      - name: Transform report file from eslint
        uses: MeilCli/common-lint-reporter/transformer/eslint@v0
        with:
          report_files: |
            eslint_report.json
          output_path: 'eslint_report.json'
      - name: Transform report file from detekt
        uses: MeilCli/common-lint-reporter/transformer/checkstyle@v0
        with:
          report_files: |
            detekt_report.xml
          output_path: 'detekt_report.json'
      - name: Report lint result
        uses: MeilCli/common-lint-reporter@v0
        with:
          report_type: 'check_run'
          report_name: 'Lint Report'
          report_files: '*_report.json'
